accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.user_login, name="user_login"),
    path('logout/', views.user_logout, name="user_logout"),
    path('register/', views.register, name="register"),
    path('dashboard/<semester>/', views.dashboard, name="dashboard"),
    path('remove/<int:subject_id>/<semester>/', views.remove_subject, name="remove_subject"),
    path('add/<int:subject_id>/<semester>/', views.add_subject, name="add_subject")
]

admission/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class UserProfileInfo(models.Model):
    GRADE = [
        ('one', 'one'),
        ('two', 'two'),
        ('three', 'three'),
        ('four', 'four'),
    ]
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    faculty = models.CharField(max_length=50)
    grade = models.CharField(max_length=5, choices=GRADE)

    def __str__(self):
        return self.user.username

class Subject(models.Model):
  name = models.CharField(max_length=50)
  hours = models.IntegerField(default = 0, blank = False)
  user = models.ManyToManyField(User, through='Membership')

  def __str__(self):
    return self.name


class Membership(models.Model):
    SEMESTER = (
        ('first', 'first'),
        ('second', 'second'),
    )
    semester = models.CharField(max_length=6, choices=SEMESTER)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

accounts/forms.py
from django import forms
from .models import UserProfileInfo
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    # password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('email',)

class UserProfileInfoForm(forms.ModelForm):
     class Meta():
         model = UserProfileInfo
         fields = ('faculty', 'grade')

accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from .forms import UserForm, UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout, password_validation
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .models import Subject, Membership, UserProfileInfo
from django.db.models import Sum
from django.contrib import messages
from django.core.mail import send_mail
import random, string

# Create your views here.
def register(request):
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            g_username = ''.join(random.choices(string.ascii_letters + string.digits, k=9))
            g_password = ''.join(random.choices(string.ascii_letters + string.digits, k=9))
            send_mail(
                'Use This username and password',
                f"Your username= {g_username} and password= {g_password}.",
                'yalanotlobiti@gmail.com',
                [user.email],
                fail_silently=False,
            )
            user.set_password(g_password)
            user.username = g_username
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            return redirect('accounts:user_login')
        else:
            context = {'user_form': user_form, 'profile_form': profile_form}
            return render(request, 'accounts/register.html', context)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
        context = {'user_form': user_form, 'profile_form':profile_form}
        return render(request,'accounts/register.html', context)


@login_required
def user_logout(request):
    logout(request)
    return redirect('accounts:user_login')

@login_required
def dashboard(request, semester):
    subjects = Subject.objects.filter(user=request.user, membership__semester=semester)
    all_subjects = Subject.objects.all()
    other_semester = 'second' if semester == 'first' else 'first'
    subjects_other_semester = Subject.objects.filter(user=request.user, membership__semester=other_semester)
    context = {
        'all_subjects': all_subjects,
        'subjects': subjects,
        'semester': semester,
        'subjects_other_semester': subjects_other_semester,
        'other_semester': other_semester
    }
    return render(request, 'accounts/dashboard.html', context)


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        print(user)
        if user:
            print(user)
            if user.is_active:
                login(request, user)
                return redirect('accounts:dashboard', semester='first')
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")

    else:
        return render(request, 'accounts/login.html', {})


def remove_subject(request, subject_id, semester):
    user = request.user
    subject = Subject.objects.get(pk=subject_id)
    m = Membership.objects.filter(user=user, subject=subject, semester=semester)
    m.delete()
    return redirect('accounts:dashboard', semester=semester)

def add_subject(request, subject_id, semester):
    reached = Subject.objects.filter(user=request.user, membership__semester=semester).aggregate(total=Sum('hours'))
    hours = 0
    if reached['total']:
        hours = reached['total']
    if hours >= 50:
        messages.error(request, "You have reached your limits for this semester  ")
        return redirect('accounts:dashboard', semester=semester)
    sub = Subject.objects.get(pk=subject_id)
    user = request.user
    Membership.objects.create(user=user, subject=sub, semester=semester)
    return redirect('accounts:dashboard', semester=semester)

accounts/templates/accounts/dashboard.html
{% extends "base/base.html" %}
{% block content %}

<div class="container">

 <div class="text-center my-4">
    <a href="{% url 'accounts:dashboard' 'first' %}" class="btn btn-info my-2" role="button">First Semester</a>
    <a href="{% url 'accounts:dashboard' 'second' %}" class="btn btn-info" role="button">Second Semester</a>
 </div>

<!--  start of messages-->
  <div class="alert alert-info text-center" role="alert">
        Max limit Of Hours For The Semester Is 50 Hours
  </div>
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-{{message.tags}} text-center" role="alert">
        {{ message }}
      </div>
    {% endfor %}
  {% endif %}
<!--  end of messages-->

<!--start of subjects-->
<div class="subjects">
    <table class="table">
      <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">subject</th>
        <th scope="col">Hours</th>
        <th scope="col">Action</th>
      </tr>
      </thead>
      <tbody>
      {% for subject in all_subjects %}
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <td> {{ subject.name }} </td>
          <td> {{ subject.hours }}</td>
          <td>
            {% if subject not in subjects_other_semester %}
              {% if subject in subjects %}
                <a class="btn btn-danger" href="{% url 'accounts:remove_subject' subject.id semester %}">Remove</a>
              {% else %}
                <a class="btn btn-info" href="{% url 'accounts:add_subject' subject.id semester %}">Add</a>
              {% endif %}
            {% else %}
              {{ other_semester }} semester
            {% endif %}
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
</div>
<!--end of subjects-->
</div>

{% endblock content %}

accounts/templates/accounts/login.html
{% extends "base/base.html" %}
{% block content %}
<section id="login" class="bg-light py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-6 mx-auto">
          <div class="card">
            <div class="card-header bg-primary text-white">
              <h4>Login</h4>
            </div>
            <div class="card-body">
              <form action="{% url 'accounts:user_login' %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                  <label for="username">Username</label>
                  <input type="text" name="username" class="form-control" required>
                </div>

                <div class="form-group">
                  <label for="password2">Password</label>
                  <input type="password" name="password" class="form-control" required>
                </div>

                <input type="submit" value="Login" class="btn btn-secondary btn-block">
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

accounts/templates/accounts/register.html
{% extends "base/base.html" %}
{% block content %}

<section id="register" class="bg-light py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-6 mx-auto">
          <div class="card">
            <div class="card-header bg-primary text-white">
              <h4>Register</h4>
            </div>

              <form action="{% url 'accounts:register' %}" method="POST" class="p-4">
                  {% csrf_token %}
                  {{ user_form.as_p }}
                  {{ profile_form.as_p }}
                  <input type="submit" name="" value="Register">
               </form>

          </div>
        </div>
      </div>
    </div>
  </section>


{% endblock content %}

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'base/css/all.css' %}">
  <!-- Bootstrap -->
  <link rel="stylesheet" href="{% static 'base/css/bootstrap.css' %}">
  <!-- Custom -->
  <link rel="stylesheet" href="{% static 'base/css/style.css' %}">

  <title>BT Real Estate</title>
</head>

<body>
  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top">
    <div class="container">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">

        {% if request.user.is_authenticated %}
        <ul class="navbar-nav">
          <li class="nav-item active mr-3">
            <a class="nav-link" href="{% url 'accounts:dashboard' 'first' %}">Dashboard</a>
          </li>
        </ul>
        {% endif %}

        {% if request.user.is_authenticated %}
          <ul class="navbar-nav ml-auto">
            <li class="nav-item mr-3">
              <a class="nav-link" href="{% url 'accounts:user_logout' %}">logout</a>
            </li>
          </ul>
        {% else %}
          <ul class="navbar-nav ml-auto">
            <li class="nav-item mr-3">
              <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
            </li>
            <li class="nav-item mr-3">
              <a class="nav-link" href="{% url 'accounts:user_login' %}">Login</a>
            </li>
          </ul>
        {% endif %}

      </div>
    </div>
  </nav>

  {% block content %}
  {% endblock content %}

  <!-- Footer -->
  <footer id="main-footer" class="py-4 bg-primary text-white text-center">
    Copyright &copy;
    <span class="year"></span> a.abdelfatah.100@gmail.com
  </footer>

  <script src="{% static 'base/js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'base/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'base/js/main.js' %}"></script>
</body>

</html>